### ISSUE TITLE
A couple Vim omissions I noticed

### ISSUE THREAD

**Issue by TylerNHansen** [clarkgrubb/hyperpolyglot#11]
Uppercase word - `gUw`
Lowercase word - `guw`
Indent line - `>>`
Indent region - visual mode `>`
Git blame on buffer: Install Git Fugitive, `:Gblame`

Uppercase and lowercase accept movements, so you could talk about `gUU` as "uppercase line"

**Comment by clarkgrubb** [comment]
Thanks, I have add this.
