### ISSUE TITLE
Java unititialized local variables are a compile-time error

### ISSUE THREAD

**Issue by rarkenin** [clarkgrubb/hyperpolyglot#15]
The statement that Java's local variables are zero when uninitialized is not correct, a compile time error occurs instead:

> If a declarator does not have an initializer, then every reference to the variable must be preceded by execution of an assignment to the variable, or a compile-time error occurs by the rules of §16 (Definite Assignment). 

From [JLS 14.4.2](http://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.4.2)

**Comment by clarkgrubb** [comment]
Thanks for pointing this out; fixed
