### ISSUE TITLE
CMD issues  (from http://hyperpolyglot.org/shell)

### ISSUE THREAD

**Issue by npocmaka** [clarkgrubb/hyperpolyglot#17]
What I see at a glance. 

#COMMENTS
::  is often  used as comment (but within brackets can cause problems -> http://ss64.com/nt/rem.html )

multi line comments are possible -> http://stackoverflow.com/questions/8526946/commenting-multiple-lines-in-dos-batch-file  . My personal favorite is break||(....) though the closing bracket can be a problem.

#IDENTIFIERS
Variable identifiers are NOT case sensitive with the exception of FOR /F command tokens -> http://ss64.com/nt/for_f.html

null within batch script %% can be used as empty variable (or !! under delayed expasnsion) . nul is an null device.

null test   (can be used also as undefined test): 
 IF DEFINED VARIABLE_NAME 
 or
 IF "%VARIABLE_NAME%" equ ""

#DIVIDE BY ZERO
prints "Divide by zero error." and sets errorlevel to 1073750993

#RANDOM

has a special dynamic variable %RANDOM% (or !RANDOM! under delayed expansion) which produces a number from 0 to 32767

#Number overflow
 in case of overflow SET /A prints "Invalid number.  Numbers are limited to 32-bits of precision."  and sets errorlevel to "1073750992" . In other cases overflow can be tricky -> http://www.dostips.com/forum/viewtopic.php?f=3&t=3758

#escapes
http://ss64.com/nt/syntax-esc.html
usually special characters are escaped with ^ . percent symbol is escapes with another percent symbol.Under delayed expansion exclamation mark is escaped with double ^^ . After piping is double escaping is needed

#variable interpolation

#sting length
You already have length function - is there a reason not to be included in the list

#index of substring
There are implemented such subroutines , but is not built-in

#extract substring

set "s=foo bar"
echo %s:~4,3%  
http://ss64.com/nt/syntax-substring.html

#string concatenation
set s1=string1
set s2=string2
set conc=%s1%%s2%

/string concatenation and sub-string are shifted in powershell section /

#number to string
everything is taken as string by SET command (without /A swith)

#regex match

FINDSTR command has a limited regex  match support

set s=hello
echo %s%|findstr /r "[a-z][a-z]*" && (echo match ) || (echo does not match) 

#regex global substitution
http://ss64.com/nt/syntax-replace.html
set "s=do re mi mi mi"
echo %s:mi=ma%

#sleep
from windows vista and above - timeout -http://ss64.com/nt/timeout.html
for nt/xp/2003 (sleep 30 seconds)
timeout /t 30 /nobreak > NUL
or 
w32tm /stripchart /computer:localhost /period:1 /dataonly /samples:30  >nul 2>&1

#functions default argument value
empty string

#exceptions raise exception
return nonzero status

#exceptions catch exception
if errorlevel 1 (
  echo something bad happened
)
 or
if %errorlevel% NEQ 1 (
  echo something bad happened
)

#uncaught exception behavior
continues with the next command

#print to standard out
echo something
or 
echo something >1

#standard file handles
1
2
3

#read line

< myfile.txt (
  set /p line1=
  set /p line2=
  set /p line3=
  set /p line4=
  set /p line5=
) 
or
for /f "delims=" %%a in (myfile.txt) do (
  echo current line:%%a
)

#read file
setlocal enableDelayedExpansion
set "file_content="
for /f "delims=" %%a in (myfile.txt) do (
  set "file_content=!file_content! %%a"
)
echo %file_content%

#write to file
	echo "hello" > \tmp\a		
#append to file	
   echo "hello" >> \tmp\a

#current directory 
     %cd% or %__cd__%			
#directory of script
     %~dp0 (if shift command is not executed)

#backticks  
 set "current_dir=%cd%"

**Comment by clarkgrubb** [comment]
thanks for the extensive feedback; this has been incorporated
