### ISSUE TITLE
code in Python regular expressions: wrong more quote '

### ISSUE THREAD

**Issue by slideclick** [clarkgrubb/hyperpolyglot#30]
named group capture:
There is a wrong  ' more:  ''foo.txt'

rx = '^(?P<file>.+)\.(?P<suffix>.+)$'
m = re.search(rx, ''foo.txt')

m.groupdict()['file']
m.groupdict()['suffix']

![image](https://cloud.githubusercontent.com/assets/7971827/8404291/6a58431c-1e7e-11e5-81dc-b03f89fff681.png)

**Comment by clarkgrubb** [comment]
Thanks, it is fixed.
