### ISSUE TITLE
Mistake in "C and Go"

### ISSUE THREAD

**Issue by noxer** [clarkgrubb/hyperpolyglot#35]
In the section "variables" the Go snippet reads:

```
 // memory allocated on heap:
 ptr := new(int)
 *ptr = 7
```

This is not always true. The Go compiler does an escape analysis on the code and only if the pointer can leave the scope of the allocating function (eg. by being returned) , the allocation is done on the heap.

**Comment by limeblack** [comment]
@noxer  I'm not familiar with Go what is the correction then?

**Comment by noxer** [comment]
You could use something like

    func alloc() *int {
        ptr := new(int)
        *ptr = 7
        return ptr
    }

That would ensure the compiler allocates ptr on the heap.

**Comment by noxer** [comment]
Timeout
