### ISSUE TITLE
Go - global variable: no such thing as file scope for variables

### ISSUE THREAD

**Issue by idubinskiy** [clarkgrubb/hyperpolyglot#49]
From https://golang.org/ref/spec#Declarations_and_scope:
> The scope of an identifier denoting a constant, type, variable, or function (but not method) declared at top level (outside any function) is the package block.

The only things that are file-scoped are imports.

Capitalization does not affect scope inside the package, it affects whether the identifier is exported (and thus available from outside the package).

**Comment by clarkgrubb** [comment]
Thanks, it is fixed.
