### ISSUE TITLE
Missing Ada Language Features/Items

### ISSUE THREAD

**Issue by OneWingedShark** [clarkgrubb/hyperpolyglot#8]
* file suffixes:

.ads -- Spec file
.adb -- Body file [implementation]
.ada -- File containing multiple compilation units or completion of SEPARATE packages/subprograms.

* block with local scope:

    declare
      x : integer; -- local variable
    begin
      null; -- operations go here.
    end;

* free memory
 
call an instantiation of `Ada.Unchecked_Deallocation` on the appropriate access type.

* conditional expression (in Ada 2012)

    (if CONDITION then VALUE_1 else VALUE_2)
    (case VARIABLE is
      when COND_1 => RESULT_1,
      when COND_2|COND_3 => RESULT_2,   -- using alternatives
      when COND_4..COND_8 => RESULT_3, -- using ranges
      when COND_9..COND_11|COND_13 => RESULT_4 -- using both
      when others => RESULT_5 -- using default; w/o an others case coverage of all possible values is enforced.
    )

* integer type

Integer

* float type

Float

* fixed type ( see: https://www2.adacore.com/gap-static/GNAT_Book/html/aarm/AA-3-5-9.html )

(user defined)
   Type Currency is delta 0.01 digits 20;

* min and max ( see: http://www.adaic.org/resources/add_content/standards/12rm/html/RM-3-5.html#I1619 )

(for S being a Scalar subtype)
S'Min( S_1, S_2 )
S'Max( S_1, S_2 )

* integer division

 3 / 7

* square root
Ada.Numerics.Elementary_Functions.Sqrt

* absolute value and sign

abs

* bounded length string type

(Given B as an instantiation of Ada.Strings.Bounded.Generic_Bounded_Length)
B.Bounded_String

* unbounded length string type

Ada.Strings.Unbounded.Unbounded_String

etc.

**Comment by clarkgrubb** [comment]
incorporated
